parameters:
  - name: imageName
  - name: registry

jobs:
  - job: Build
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - task: Docker@2
        displayName: 'Login to Amazon ECR'
        inputs:
          command: 'login'
          containerRegistry: '<your-ecr-service-connection>'
      - task: Docker@2
        displayName: 'Build and Push'
        inputs:
          command: 'buildAndPush'
          repository: '$(parameters.imageName)'
          dockerfile: 'Dockerfile'
          containerRegistry: '<your-ecr-service-connection>'
          tags: 'latest'
