parameters:
  - name: namespace
  - name: imageName
  - name: registry
  - name: kubernetesServiceEndpoint

jobs:
  - job: Deploy
    displayName: 'Deploy to $(parameters.namespace)'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Kubernetes@1
        displayName: 'Set Image in Kubernetes Deployment'
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: $(parameters.kubernetesServiceEndpoint)
          namespace: $(parameters.namespace)
          command: 'set'
          arguments: "image deployment/my-app my-app=$(parameters.registry)/$(parameters.imageName):latest"

      - task: Kubernetes@1
        displayName: 'Apply Kubernetes Deployment'
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: $(parameters.kubernetesServiceEndpoint)
          namespace: $(parameters.namespace)
          command: 'apply'
          useConfigurationFile: true
          configuration: 'k8s/deployment.yaml'
